#!/bin/sh

HYPRLAND_DEVICE="SynPS/2 Synaptics TouchPad"

if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

enable_touchpad() {
  printf "true" > "$STATUS_FILE"

  notify-send -u normal "Enabling Touchpad"

  hyprctl keyword "device:$HYPRLAND_DEVICE:enabled" true
}

disable_touchpad() {
  printf "false" > "$STATUS_FILE"

  notify-send -u normal "Disabling Touchpad"

  hyprctl keyword "device:$HYPRLAND_DEVICE:enabled" false
}

# Add debug statement
echo "STATUS_FILE: $STATUS_FILE"

if ! [ -f "$STATUS_FILE" ]; then
  echo "Status file not found, enabling touchpad"
  enable_touchpad
else
  current_status=$(cat "$STATUS_FILE")
  echo "Current status: $current_status"

  if [ "$current_status" = "true" ]; then
    echo "Touchpad is currently enabled, disabling it"
    disable_touchpad
  elif [ "$current_status" = "false" ]; then
    echo "Touchpad is currently disabled, enabling it"
    enable_touchpad
  else
    echo "Unknown status found: $current_status"
  fi
fi

