#!/bin/bash

iDIR="$HOME/.config/dunst/icons"

# Get brightness
get_backlight() {
  #brightnessctl -m -d device_name | awk -F, '{print substr($4, 0, length($4)-1)}' ##device_name can be found using \
  #$(brightnessctl -l | grep backlight)
  light=$(brightnessctl -m | grep -o '[0-9]\+%' | head -c-2)
  echo "${light}%"
}

# Get icons
get_icon() {
	current="$(brightnessctl g)"
	if [[ ("$current" -ge "0") && ("$current" -le "4800") ]]; then
		echo "$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "4800") && ("$current" -le "9600") ]]; then
		echo "$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "9600") && ("$current" -le "14400") ]]; then
		echo "$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "14400") && ("$current" -le "19200") ]]; then
		echo "$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "19200") && ("$current" -le "24000") ]]; then
		echo "$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
