#!/bin/sh
#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Lavender-Dark"
gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-dark"
#change the background image and be cool about it ;)
killall swaybg
swaybg -m fill -i ~/Pictures/wallpapers/axo1.png