#!/bin/sh
#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Latte-Standard-Lavender-Light"
gsettings set org.gnome.desktop.interface icon-theme "WhiteSur"
#change the background image and be cool about it ;)
killall swaybg
swaybg -m fill -i ~/Pictures/wallpapers/axo2.png