#!/bin/sh

iDIR="$HOME/.config/waybar/icons"

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	printf "%s\n" "$volume"
}

# Get icons
get_icon() {
	current=$(get_volume)
	if [ "$current" -eq "0" ]; then
		printf "%s\n" "$iDIR/volume-mute.png"
	elif [ "$current" -ge "0" ] && [ "$current" -le "30" ]; then
		printf "%s\n" "$iDIR/volume-low.png"
	elif [ "$current" -ge "30" ] && [ "$current" -le "60" ]; then
		printf "%s\n" "$iDIR/volume-mid.png"
	elif [ "$current" -ge "60" ] && [ "$current" -le "100" ]; then
		printf "%s\n" "$iDIR/volume-high.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume) %"
}

# Increase Volume
inc_volume() {
	pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
	pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" = "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
	elif [ "$(pamixer --get-mute)" = "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --default-source --get-mute)" = "false" ]; then
		pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
	elif [ "$(pamixer --default-source --get-mute)" = "true" ]; then
		pamixer -u --default-source u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
	fi
}

# Get mic icons
get_mic_icon() {
	current=$(pamixer --default-source --get-volume)
	if [ "$current" -eq "0" ]; then
		printf "%s\n" "$iDIR/microphone.png"
	elif [ "$current" -ge "0" ] && [ "$current" -le "30" ]; then
		printf "%s\n" "$iDIR/microphone.png"
	elif [ "$current" -ge "30" ] && [ "$current" -le "60" ]; then
		printf "%s\n" "$iDIR/microphone.png"
	elif [ "$current" -ge "60" ] && [ "$current" -le "100" ]; then
		printf "%s\n" "$iDIR/microphone.png"
	fi
}

# Notify
notify_mic_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(pamixer --default-source --get-volume) %"
}

# Increase MIC Volume
inc_mic_volume() {
	pamixer --default-source -i 5 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
	pamixer --default-source -d 5 && notify_mic_user
}

# Execute accordingly
case "$1" in
	--get)
		get_volume
		;;
	--inc)
		inc_volume
		;;
	--dec)
		dec_volume
		;;
	--toggle)
		toggle_mute
		;;
	--toggle-mic)
		toggle_mic
		;;
	--get-icon)
		get_icon
		;;
	--get-mic-icon)
		get_mic_icon
		;;
	--mic-inc)
		inc_mic_volume
		;;
	--mic-dec)
		dec_mic_volume
		;;
	*)
		get_volume
		;;
esac

