#!/bin/bash
# Game Mode. Turning off all animations

notif="$HOME/.config/swaync/images/gamemode.png"
SCRIPTSDIR="$HOME/.config/hypr/scripts"


HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
	
	hyprctl keyword "windowrule opacity 1 override 1 override 1 override, ^(.*)$"
    swww kill
    sleep 0.1
    killall waybar
    notify-send -e -u low -i "$notif" " Gamemode:" " enabled"
    exit
else
	waypaper --restore 
	sleep 0.1
	waybar &
	sleep 0.5
	swaync > /dev/null 2>&1 &
	swaync-client --reload-config
	hyprctl reload
    notify-send -e -u normal -i "$notif" " Gamemode:" " disabled"
    exit
fi
hyprctl reload
